spring:
  datasource:
    password: qwerty25
    url: jdbc:postgresql://localhost:5432/carsDB
    username: postgres
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:import.sql
      enabled: true
